"""create resource metrics table

Revision ID: 5f78f50f5134
Revises: 3d807717c26a
Create Date: 2026-08-17 10:57:33.240595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f78f50f5134'
down_revision: Union[str, Sequence[str], None] = '3d807717c26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=False),
    sa.Column('memory_usage_percent', sa.Float(), nullable=False),
    sa.Column('storage_usage_percent', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_metrics_id'), 'resource_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_resource_metrics_resource_id'), 'resource_metrics', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_metrics_resource_id'), table_name='resource_metrics')
    op.drop_index(op.f('ix_resource_metrics_id'), table_name='resource_metrics')
    op.drop_table('resource_metrics')
    # ### end Alembic commands ###
